/* groovylint-disable LineLength, NestedBlockDepth */
pipeline {
    agent any
    stages {
        stage('Verify SCM changes for Python') {
            when {
                expression {   // ...check if chages are not in python
                    sh(returnStdout: true, script: 'git diff origin/main --name-only | grep -c "^python/.*"') == '0'
                }
            }
            steps {
                script {
                    currentBuild.result = 'ABORTED'
                    error('Aborting the build.')
                }
            }
        }
        stage('Build Python') {
            steps {
                echo 'Building Python'
            }
        }
    }
    post {
        always {
            echo 'Do stuff before you die!!!'
        }
    }
}
