/* groovylint-disable LineLength, NestedBlockDepth */
pipeline {
    agent any
    environment {
        SHOULD_SKIP = false
    }
    stages {
        stage('Verify SCM changes for Python') {
            when {
                expression {   // ...check if chages are not in python
                    sh(returnStdout: true, script: 'git diff origin/main --name-only | grep -c "^python/.*"') == '0'
                }
            }
            steps {
                script {
                    env.SHOULD_SKIP = true
                }
            }
        }
        stage('Build Python') {
            when {
                expression { env.SHOULD_SKIP == false }
            }
            steps {
                echo 'Building Python'
            }
        }
    }
    post {
        always {
            echo 'Do stuff before you die!!!'
        }
    }
}
