/* groovylint-disable LineLength, NestedBlockDepth */
pipeline {
    agent any
    environment {
        SHOULD_SKIP = 'false'
    }
    stages {
        stage('Verify SCM changes for Python') {
            when {
                expression {   // ...check if chages are not in python
                    sh(returnStdout: true, returnStatus: true, script: 'git diff origin/main --name-only | grep -c "^python/.*"').trim() == '0'
                }
            }
            steps {
                script {
                    echo 'mutating env variable SHOULD_SKIP'
                    env.SHOULD_SKIP = 'true'
                }
            }
        }
        stage('Build Python') {
            when {
                environment name: 'SHOULD_SKIP', value: 'false'
            }
            steps {
                echo 'Building Python'
            }
        }
    }
    post {
        always {
            echo 'Do stuff before you die!!!'
        }
    }
}
